void setup() {
  Serial.begin(9600);
  pinMode(5,OUTPUT);
   pinMode(6,OUTPUT);
    pinMode(7,OUTPUT);
     pinMode(8,OUTPUT);
      pinMode(9,OUTPUT);
       pinMode(10,OUTPUT);
        pinMode(11,OUTPUT);
         pinMode(12,OUTPUT);
}

void loop() {
 if(Serial.available()){
  int deger=Serial.read();
  if (deger=='1')
  {
  
    digitalWrite(5,HIGH);
     digitalWrite(6,LOW);
      digitalWrite(7,LOW);
       digitalWrite(8,LOW);
        digitalWrite(9,LOW);
         digitalWrite(10,LOW);
          digitalWrite(11,LOW);
           digitalWrite(12,LOW);
            digitalWrite(13,LOW);
  }
  if(deger=='2')
  {
    digitalWrite(5,LOW);
     digitalWrite(6,HIGH);
      digitalWrite(7,LOW);
       digitalWrite(8,LOW);
        digitalWrite(9,LOW);
         digitalWrite(10,LOW);
          digitalWrite(11,LOW);
           digitalWrite(12,LOW);
            digitalWrite(13,LOW);
  }
  if(deger=='3')
  {
    digitalWrite(5,LOW);
     digitalWrite(6,LOW);
      digitalWrite(7,HIGH);
       digitalWrite(8,LOW);
        digitalWrite(9,LOW);
         digitalWrite(10,LOW);
          digitalWrite(11,LOW);
           digitalWrite(12,LOW);
            digitalWrite(13,LOW);
  }
  if(deger=='4')
  {digitalWrite(5,LOW);
     digitalWrite(6,LOW);
      digitalWrite(7,LOW);
       digitalWrite(8,HIGH);
        digitalWrite(9,LOW);
         digitalWrite(10,LOW);
          digitalWrite(11,LOW);
           digitalWrite(12,LOW);
            digitalWrite(13,LOW);
  }
  if(deger=='5')
  {
    digitalWrite(5,LOW);
     digitalWrite(6,LOW);
      digitalWrite(7,LOW);
       digitalWrite(8,LOW);
        digitalWrite(9,HIGH);
         digitalWrite(10,LOW);
          digitalWrite(11,LOW);
           digitalWrite(12,LOW);
            digitalWrite(13,LOW);
  }
  if(deger=='6')
  {
    digitalWrite(5,LOW);
     digitalWrite(6,LOW);
      digitalWrite(7,LOW);
       digitalWrite(8,LOW);
        digitalWrite(9,LOW);
         digitalWrite(10,HIGH);
          digitalWrite(11,LOW);
           digitalWrite(12,LOW);
            digitalWrite(13,LOW);
  }
  if(deger=='7')
  {
    digitalWrite(5,LOW);
     digitalWrite(6,LOW);
      digitalWrite(7,LOW);
       digitalWrite(8,LOW);
        digitalWrite(9,LOW);
         digitalWrite(10,LOW);
          digitalWrite(11,HIGH);
           digitalWrite(12,LOW);
            digitalWrite(13,LOW);
  }
  if(deger=='8')
  {
    digitalWrite(5,LOW);
     digitalWrite(6,LOW);
      digitalWrite(7,LOW);
       digitalWrite(8,LOW);
        digitalWrite(9,LOW);
         digitalWrite(10,LOW);
          digitalWrite(11,LOW);
           digitalWrite(12,HIGH);
            digitalWrite(13,LOW);
  }
  if(deger=='9')
  {
    digitalWrite(5,LOW);
     digitalWrite(6,LOW);
      digitalWrite(7,LOW);
       digitalWrite(8,LOW);
        digitalWrite(9,LOW);
         digitalWrite(10,LOW);
          digitalWrite(11,LOW);
           digitalWrite(12,LOW);
            digitalWrite(13,HIGH);
  }
  if(deger=='0')
  {
    digitalWrite(5,LOW);
     digitalWrite(6,LOW);
      digitalWrite(7,LOW);
       digitalWrite(8,LOW);
        digitalWrite(9,LOW);
         digitalWrite(10,LOW);
          digitalWrite(11,LOW);
           digitalWrite(12,LOW);
            digitalWrite(13,LOW);
  }}}
  
